language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo

env:
  global:
  - DEPLOY_BRANCH="master"
  # BUCKET_NAME
  - secure: "B21+FzDj1VBcxdSr4hsz3yKnPEk/M87ffuZ560gCaZoKo69p8Iq5SebVQgw4iNkGMkvW0qC/bvqcEBnIQiSYP62SXsoLMTvO2rTHYrdO4jgwmf5A31fe1uha2h2FYxzbRgAPWEEPx9zYv+adUMWmiyhSF5GbJ6k9dEHn+C1GFVL0sLxs3eC2JIAdcKdA9BIllhQcC18SvzdI/tNRqFmLIn3YatHTvmsFOoqfUCPfM08Fezmb9sZJ0j4cPIG+JsPPj5KrzY9HFShpG2lWIjY7+axeUpsqU7JlYx4bYjSSdrAZcBxFWF1WdPvXeTMrBwXdy9jTQ3b1mcVG5FhU8vCK9EHZY/OMRNiXSjPicbTUfl7GZt2HfrSB9GqtafgrWQ4HOMymgsMJHxmPVcrZU2pGcb3/eNPoRcZ3KNPL4K4ZMNtJQ9LT/JXPnrMc3V2nAxYAyutS3iQsJOffgy6co/rN+W/owqSlS3VeWIJSUKeP64KW9VyckqFLbLlT1HYviv8YK9uwOgH1qzYGrvw5TJD7nUzMlkwSOAtOiU7RaxCQKdnxVLHnFficY8dIaIQewUkkqIxedHQ9JtOAXD3awenv/j7eQ4KTCmozGllji3Ep43YK+q7oQwjClmCoyrwl6blHhy1doeULpmNx/bP2jaUN6TMfdehE99slBPJT7wkHdQg="
  # DISTRIBUTION_ID
  - secure: "uHNmN5MvPLK5mJJN3KnR0CF8FaY7gDSV/3M/2/lum2CAJaYpQsKdukeM0gMNXgQPmnikQxuQUdXGM044qlNmhcQRKqnydK8K4ikEj2q3bYUQRzYWUMPn0l+iuUZMAH7ZEBcMUTTuLNctDgEoE4K5TxdIJ2rOQBMNT+4DuB429HcVIGZAyI0vS6q2QmHwAJ0e9OPe/5u3vpq7qyG8cO0Bv/lb73edZR1H57YesPrr9t6GHm3YUbo5cBu5TfqPUgzIXiPim7F9/6vUOlH/ZbWjqPq8/SN45lC6XCAtmrk4A2naQp+wFMK2VaEs9IR152MaFE8low+BYvf9UD9sPaDv4uE5PQEqaQbEtX3TZVisTkIGd7aOGEb3o8sER9u45a8K98AOXSlG6fTIspw0khy7n873hf3aB07nNXHuceTKcxFC33mD4JDQ3AKBN+vPU6dH8FpHfFRK3v24ySk9KhB7y7Mo5Aw4IX6kJyGPlxCyT6JpDlSSVN+IG55Y79tEw9V++Tq1rtsmIglVes1s+tsP4pLRCwXSEAmVsKibcaNwxcTAn6kaA8b7WbBInYTr1u4NF1kVoH4038e2ZgTkmGpwKdl019CvWo7PvvM7vGrL79mkmQZwD862LxWdNWJNXwGq9t3owhG5CL/nRv+Sos5iigBlW8xii6EwEmZ8RO4Mc/c="
  # ACCESS KEY
  - secure: "UfPs4C8RKwDD+4f5xJ0z/grd+IC1dy3UETHJOqwgKKnwv4Xca0FDt7c54SXDqjgO7rOt7w+mrMmdQ/dikfzOrQ/3tqs+n4yuiJ0Pr0a3kGtILozIDEM7nHhXdjkIFkXXx+i5LFUZxflKhqaJBxInrXFe/zASjEMpNZhAdS+mJOlZNDJClG8dZQmsk/R67bFRoe4kDh+MAkuxpK99Btf0juzDcTBOX5Nay6RV/BXaJfztR1tphVh0eLMeZhMxhgRVgeuyJzfO0kfftiigWo8cDGUwJTOAduV/vGKfp72EvztPWVpIKhIVxtRvudiy6aSh/meFipeZu7Qe738ju8yB6ScQRWtrV2G0bDc96dVXYe4Z6nB43OzKJ3oXlP5zNAOg5KfZq6VumQKIDvunfR/50AiD3H6KX/AxZiXEte0qZnVYq7smwHe6qYKLHAydnBdpSZA+ZKcg0NZ/Vi/fyQLeZpCJXE6yx8nd3NPCjX1VYUsTRGSQKKqPqQ27zOWZPJ0KOiplf7K+rDJXLrmVZAdJW0QpZUncmh6nUx7IqNAv8xAI7lCjh/wgJpoIzebuLtVoiz3kIafFC3nOUA1mUYmgxHcqypyt2+NGvgVQinyMH8eSla/YGAHXMqKReWtMbGUXYRWx0rYP3LepzS2bpCvFCj0ExOVVN/v6+/Fgqw6/0WI="
  # ACCESS ID
  - secure: "d065Gh3r9FR2vV88MjV3ZRSPb41yswcaOjaF71wQaGHgzqh92aGTcw9betmFvz0+UvJX4vGGRFnamlCqA45tIngvxdX4fNhfun/h+JS+jGNBGepEGxE6hcAWEab/FuPNSh5d2f+6nTRz4MfJ75aQLx6IRs27fuUoyhdw85xngcSQYQOYXibB3hT4YkOqKH+2HndFsmbn7es2lJfYVQTrPqXVVWDzNnN0hDbBvKCfT7YGzcwmy9Lneei80NEjzqyjImXiBMmB414u3bSHJkO1FaAFMRS91P9rN/B+DQnlEcqpxRebA45XMq4ROUGoExuwCWv4EgW4x6/nO32ztVJ4p859EUCS6TjMoWsseuy2dUIEGa7gB+gfuuMf7FX6Y2cCB+AmUj0xo0lDGhsrb9le5D/Rmoy7OAjtuRxQ45PHQNYDPzGyEtC/es8idShbt4GzZ8co31uuvj4Tf1wmPjKlXaFDu7tbV/8aLSBdqcZjY7M9i1NELCCPu4Sup9JCxgolpS+cL3OOVjhRPF34VmkQ9qXTvxcS42zfZB61x6Y6nE5xiN6Qxt96hziqe/egPvl54bMMec/gHhojlxKjnJ8/vT5kswigsEHmCI/BrXRv0wSjtm9r1UQv84EJcM2xZEKmvHV/g4AwCN5fiUirGomRCGSqVpwoOuNOlWrG96f9WME="

before_deploy:
  - pip install awscli
deploy:
  provider: script
  script: scripts/deploy
  skip_cleanup: true
  on:
    branch: master
