baseURL = "https://www.bater.io/"
languageCode = "en-us"
title = "Kirk Bater"
theme = "hyde"
googleAnalytics = "UA-112318786-1"

[author]
  name = "Kirk Bater"
  github = "iamkirkbater"
  twitter = "KirkBater"
  linkedin = "kirkbater"

[permalinks]
  posts = "posts/:year/:month/:title/"
  pages = ":slug/"

[params]
  layoutReverse = true
  description = "Polyglot Software Engineer; Woodworker; Triathlete; Eater of Foods"
  github_user = "iamkirkbater"
  css = ["css/blog.css"]
  social = [
    "twitter-summary-card"
  ]
